org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.83
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_name=Miners Delight
mod_id=minersdelight
mod_version=1.3.0
mod_license=MIT License
mod_group_id=com.sammy.minersdelight
mod_authors=Sammy;, Soytutta
mod_description=A cozy cavern focused cooking expansion for Farmer's Delight!

# Mandatory
lodestone_version=1.7.2.391
lodestone_version_range=[1.7.0,)

curios_version=9.3.1+1.21.1

registrate_version = MC1.21-1.3.0+62

# Misc
jei_version=19.21.0.247
fusion_version=1.1.1